In [3]:
pip install pandas numpy pyarrow duckdb matplotlib seaborn scikit-learn

Requirement already satisfied: pandas in c:\users\parma\appdata\local\programs\python\python313\lib\site-packages (3.0.5)
Requirement already satisfied: numpy in c:\users\parma\appdata\local\programs\python\python313\lib\site-packages (2.5.2)
Requirement already satisfied: pyarrow in c:\users\parma\appdata\local\programs\python\python313\lib\site-packages (25.0.1)
Requirement already satisfied: duckdb in c:\users\parma\appdata\local\programs\python\python313\lib\site-packages (1.5.5)
Requirement already satisfied: matplotlib in c:\users\parma\appdata\local\programs\python\python313\lib\site-packages (3.11.1)
Requirement already satisfied: seaborn in c:\users\parma\appdata\local\programs\python\python313\lib\site-packages (0.13.2)
Requirement already satisfied: scikit-learn in c:\users\parma\appdata\local\programs\python\python313\lib\site-packages (1.9.0)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\parma\appdata\roaming\python\python313\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in c:\users\parma\appdata\local\programs\python\python313\lib\site-packages (from pandas) (2026.3)
Requirement already satisfied: contourpy>=1.0.1 in c:\users\parma\appdata\local\programs\python\python313\lib\site-packages (from matplotlib) (1.3.3)
Requirement already satisfied: cycler>=0.10 in c:\users\parma\appdata\local\programs\python\python313\lib\site-packages (from matplotlib) (0.12.1)
Requirement already satisfied: fonttools>=4.28.2 in c:\users\parma\appdata\local\programs\python\python313\lib\site-packages (from matplotlib) (4.64.0)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\users\parma\appdata\local\programs\python\python313\lib\site-packages (from matplotlib) (1.5.1)
Requirement already satisfied: packaging>=20.0 in c:\users\parma\appdata\roaming\python\python313\site-packages (from matplotlib) (26.3)
Requirement already satisfied: pillow>=9 in c:\users\parma\appdata\local\programs\python\python313\lib\site-packages (from matplotlib) (12.3.0)
Requirement already satisfied: pyparsing>=3 in c:\users\parma\appdata\local\programs\python\python313\lib\site-packages (from matplotlib) (3.3.2)
Requirement already satisfied: scipy>=1.10.0 in c:\users\parma\appdata\local\programs\python\python313\lib\site-packages (from scikit-learn) (1.18.1)
Requirement already satisfied: joblib>=1.4.0 in c:\users\parma\appdata\local\programs\python\python313\lib\site-packages (from scikit-learn) (1.6.0)
Requirement already satisfied: narwhals>=2.0.1 in c:\users\parma\appdata\local\programs\python\python313\lib\site-packages (from scikit-learn) (2.25.0)
Requirement already satisfied: threadpoolctl>=3.5.0 in c:\users\parma\appdata\local\programs\python\python313\lib\site-packages (from scikit-learn) (3.6.0)
Requirement already satisfied: cloudpickle>=3.0 in c:\users\parma\appdata\local\programs\python\python313\lib\site-packages (from joblib>=1.4.0->scikit-learn) (3.1.2)
Requirement already satisfied: six>=1.5 in c:\users\parma\appdata\roaming\python\python313\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.1.1 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [4]:
import pandas as pd

In [5]:
file_path = "../Datasets/Jan2025.csv"

df = pd.read_csv(file_path)

FileNotFoundError: [Errno 2] No such file or directory: '../Datasets/Jan2025.csv'

In [ ]:
df.head()

,YEAR,MONTH,FL_DATE,OP_UNIQUE_CARRIER,OP_CARRIER_FL_NUM,ORIGIN_AIRPORT_ID,ORIGIN,ORIGIN_CITY_NAME,ORIGIN_STATE_ABR,ORIGIN_STATE_NM,...,FIRST_DEP_TIME,TOTAL_ADD_GTIME,LONGEST_ADD_GTIME,DIV_AIRPORT_LANDINGS,DIV_REACHED_DEST,DIV_ACTUAL_ELAPSED_TIME,DIV_ARR_DELAY,DIV_DISTANCE,DIV1_AIRPORT,DIV1_AIRPORT_ID
0,2025,1,1/1/2025 12:00:00 AM,AA,1,12478,JFK,"New York, NY",NY,New York,...,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN
1,2025,1,1/1/2025 12:00:00 AM,AA,10,12892,LAX,"Los Angeles, CA",CA,California,...,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN
2,2025,1,1/1/2025 12:00:00 AM,AA,1002,13485,MSN,"Madison, WI",WI,Wisconsin,...,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN
3,2025,1,1/1/2025 12:00:00 AM,AA,1004,14100,PHL,"Philadelphia, PA",PA,Pennsylvania,...,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN
4,2025,1,1/1/2025 12:00:00 AM,AA,1005,13930,ORD,"Chicago, IL",IL,Illinois,...,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
df.shape

(539747, 54)

In [ ]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 539747 entries, 0 to 539746
Data columns (total 54 columns):
 #   Column                   Non-Null Count   Dtype
---  ------                   --------------   -----
 0   YEAR                     539747 non-null  int64
 1   MONTH                    539747 non-null  int64
 2   FL_DATE                  539747 non-null  str
 3   OP_UNIQUE_CARRIER        539747 non-null  str
 4   OP_CARRIER_FL_NUM        539747 non-null  int64
 5   ORIGIN_AIRPORT_ID        539747 non-null  int64
 6   ORIGIN                   539747 non-null  str
 7   ORIGIN_CITY_NAME         539747 non-null  str
 8   ORIGIN_STATE_ABR         539747 non-null  str
 9   ORIGIN_STATE_NM          539747 non-null  str
 10  DEST_AIRPORT_ID          539747 non-null  int64
 11  DEST                     539747 non-null  str
 12  DEST_CITY_NAME           539747 non-null  str
 13  DEST_STATE_ABR           539747 non-null  str
 14  CRS_DEP_TIME             539747 non-null  int64
 15  DEP_TIME                 523861 non-null  float64
 16  DEP_DELAY                523824 non-null  float64
 17  DEP_DELAY_NEW            523824 non-null  float64
 18  DEP_DEL15                523824 non-null  float64
 19  DEP_DELAY_GROUP          523824 non-null  float64
 20  DEP_TIME_BLK             539747 non-null  str
 21  TAXI_OUT                 523520 non-null  float64
 22  WHEELS_OFF               523520 non-null  float64
 23  WHEELS_ON                523167 non-null  float64
 24  TAXI_IN                  523167 non-null  float64
 25  CRS_ARR_TIME             539747 non-null  int64
 26  ARR_TIME                 523167 non-null  float64
 27  ARR_DELAY                522269 non-null  float64
 28  ARR_DELAY_NEW            522269 non-null  float64
 29  ARR_DEL15                522269 non-null  float64
 30  ARR_TIME_BLK             539747 non-null  str
 31  CANCELLED                539747 non-null  float64
 32  CANCELLATION_CODE        16312 non-null   str
 33  DIVERTED                 539747 non-null  float64
 34  CRS_ELAPSED_TIME         539747 non-null  float64
 35  ACTUAL_ELAPSED_TIME      522269 non-null  float64
 36  AIR_TIME                 522269 non-null  float64
 37  FLIGHTS                  539747 non-null  float64
 38  DISTANCE                 539747 non-null  float64
 39  CARRIER_DELAY            98130 non-null   float64
 40  WEATHER_DELAY            98130 non-null   float64
 41  NAS_DELAY                98130 non-null   float64
 42  SECURITY_DELAY           98130 non-null   float64
 43  LATE_AIRCRAFT_DELAY      98130 non-null   float64
 44  FIRST_DEP_TIME           4267 non-null    float64
 45  TOTAL_ADD_GTIME          4267 non-null    float64
 46  LONGEST_ADD_GTIME        4267 non-null    float64
 47  DIV_AIRPORT_LANDINGS     539747 non-null  int64
 48  DIV_REACHED_DEST         1166 non-null    float64
 49  DIV_ACTUAL_ELAPSED_TIME  898 non-null     float64
 50  DIV_ARR_DELAY            898 non-null     float64
 51  DIV_DISTANCE             1166 non-null    float64
 52  DIV1_AIRPORT             1252 non-null    str
 53  DIV1_AIRPORT_ID          1252 non-null    float64
dtypes: float64(33), int64(8), str(13)
memory usage: 266.3 MB

In [ ]:
df.columns.tolist()

['YEAR',
 'MONTH',
 'FL_DATE',
 'OP_UNIQUE_CARRIER',
 'OP_CARRIER_FL_NUM',
 'ORIGIN_AIRPORT_ID',
 'ORIGIN',
 'ORIGIN_CITY_NAME',
 'ORIGIN_STATE_ABR',
 'ORIGIN_STATE_NM',
 'DEST_AIRPORT_ID',
 'DEST',
 'DEST_CITY_NAME',
 'DEST_STATE_ABR',
 'CRS_DEP_TIME',
 'DEP_TIME',
 'DEP_DELAY',
 'DEP_DELAY_NEW',
 'DEP_DEL15',
 'DEP_DELAY_GROUP',
 'DEP_TIME_BLK',
 'TAXI_OUT',
 'WHEELS_OFF',
 'WHEELS_ON',
 'TAXI_IN',
 'CRS_ARR_TIME',
 'ARR_TIME',
 'ARR_DELAY',
 'ARR_DELAY_NEW',
 'ARR_DEL15',
 'ARR_TIME_BLK',
 'CANCELLED',
 'CANCELLATION_CODE',
 'DIVERTED',
 'CRS_ELAPSED_TIME',
 'ACTUAL_ELAPSED_TIME',
 'AIR_TIME',
 'FLIGHTS',
 'DISTANCE',
 'CARRIER_DELAY',
 'WEATHER_DELAY',
 'NAS_DELAY',
 'SECURITY_DELAY',
 'LATE_AIRCRAFT_DELAY',
 'FIRST_DEP_TIME',
 'TOTAL_ADD_GTIME',
 'LONGEST_ADD_GTIME',
 'DIV_AIRPORT_LANDINGS',
 'DIV_REACHED_DEST',
 'DIV_ACTUAL_ELAPSED_TIME',
 'DIV_ARR_DELAY',
 'DIV_DISTANCE',
 'DIV1_AIRPORT',
 'DIV1_AIRPORT_ID']

In [ ]:
df.isna().sum()

YEAR                            0
MONTH                           0
FL_DATE                         0
OP_UNIQUE_CARRIER               0
OP_CARRIER_FL_NUM               0
ORIGIN_AIRPORT_ID               0
ORIGIN                          0
ORIGIN_CITY_NAME                0
ORIGIN_STATE_ABR                0
ORIGIN_STATE_NM                 0
DEST_AIRPORT_ID                 0
DEST                            0
DEST_CITY_NAME                  0
DEST_STATE_ABR                  0
CRS_DEP_TIME                    0
DEP_TIME                    15886
DEP_DELAY                   15923
DEP_DELAY_NEW               15923
DEP_DEL15                   15923
DEP_DELAY_GROUP             15923
DEP_TIME_BLK                    0
TAXI_OUT                    16227
WHEELS_OFF                  16227
WHEELS_ON                   16580
TAXI_IN                     16580
CRS_ARR_TIME                    0
ARR_TIME                    16580
ARR_DELAY                   17478
ARR_DELAY_NEW               17478
ARR_DEL15                   17478
ARR_TIME_BLK                    0
CANCELLED                       0
CANCELLATION_CODE          523435
DIVERTED                        0
CRS_ELAPSED_TIME                0
ACTUAL_ELAPSED_TIME         17478
AIR_TIME                    17478
FLIGHTS                         0
DISTANCE                        0
CARRIER_DELAY              441617
WEATHER_DELAY              441617
NAS_DELAY                  441617
SECURITY_DELAY             441617
LATE_AIRCRAFT_DELAY        441617
FIRST_DEP_TIME             535480
TOTAL_ADD_GTIME            535480
LONGEST_ADD_GTIME          535480
DIV_AIRPORT_LANDINGS            0
DIV_REACHED_DEST           538581
DIV_ACTUAL_ELAPSED_TIME    538849
DIV_ARR_DELAY              538849
DIV_DISTANCE               538581
DIV1_AIRPORT               538495
DIV1_AIRPORT_ID            538495
dtype: int64

In [ ]:
df["OP_UNIQUE_CARRIER"].nunique()

14

In [ ]:
df["ORIGIN"].nunique()

329

In [ ]:
df["DEST"].nunique()

329

In [ ]:
df["CANCELLED"].value_counts()

CANCELLED
0.0    523435
1.0     16312
Name: count, dtype: int64

In [ ]:
df["DIVERTED"].value_counts()

DIVERTED
0.0    538581
1.0      1166
Name: count, dtype: int64

In [ ]:
df["ARR_DEL15"].value_counts(dropna=False)

ARR_DEL15
0.0    424139
1.0     98130
NaN     17478
Name: count, dtype: int64

In [ ]:
df["DEP_DEL15"].value_counts(dropna=False)

DEP_DEL15
0.0    428164
1.0     95660
NaN     15923
Name: count, dtype: int64

In [ ]:
pd.crosstab(df["CANCELLED"], df["ARR_DEL15"], dropna=False)

ARR_DEL15     0.0    1.0    NaN
CANCELLED
0.0        424139  98130   1166
1.0             0      0  16312

In [ ]:
pd.crosstab(df["DIVERTED"], df["ARR_DEL15"], dropna=False)

ARR_DEL15     0.0    1.0    NaN
DIVERTED
0.0        424139  98130  16312
1.0             0      0   1166

In [ ]:
pd.crosstab(df["CANCELLED"], df["DEP_DEL15"], dropna=False)

DEP_DEL15     0.0    1.0    NaN
CANCELLED
0.0        428003  95432      0
1.0           161    228  15923

In [ ]:
pd.crosstab(df["CANCELLED"], df["DIVERTED"])

DIVERTED      0.0   1.0
CANCELLED
0.0        522269  1166
1.0         16312     0

In [ ]:
df["OP_UNIQUE_CARRIER"].nunique()

14

In [ ]:
df["OP_UNIQUE_CARRIER"].value_counts()

OP_UNIQUE_CARRIER
WN    105307
DL     76306
AA     75088
OO     65036
UA     62007
YX     27833
MQ     21890
OH     21094
AS     18163
B6     17918
NK     17544
F9     15526
G4      9345
HA      6690
Name: count, dtype: int64

In [ ]:
df["ORIGIN"].nunique()
df["DEST"].nunique()
df["ORIGIN"].value_counts().head(20)

ORIGIN
DFW    25124
DEN    24732
ATL    23881
ORD    21643
CLT    16877
PHX    15956
LAX    15157
LAS    15007
MCO    13058
SEA    11882
DCA    11734
LGA    10905
SFO    10839
BOS    10624
MIA    10182
EWR    10144
SLC     9350
DTW     9253
IAH     9250
MSP     8483
Name: count, dtype: int64

In [ ]:
df["DEST"].value_counts().head(20)

DEST
DFW    25125
DEN    24740
ATL    23881
ORD    21641
CLT    16883
PHX    15949
LAX    15143
LAS    15004
MCO    13052
SEA    11893
DCA    11740
LGA    10909
SFO    10832
BOS    10622
MIA    10184
EWR    10139
SLC     9347
IAH     9257
DTW     9254
MSP     8480
Name: count, dtype: int64

In [ ]:
df["FL_DATE"] = pd.to_datetime(df["FL_DATE"])

df["FL_DATE"].head()

C:\Users\parma\AppData\Local\Temp\ipykernel_36748\2795176422.py:1: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df["FL_DATE"] = pd.to_datetime(df["FL_DATE"])

0   2025-01-01
1   2025-01-01
2   2025-01-01
3   2025-01-01
4   2025-01-01
Name: FL_DATE, dtype: datetime64[us]

In [ ]:
df["FL_DATE"].dtype

dtype('<M8[us]')

In [ ]:
df["YEAR"] = df["FL_DATE"].dt.year
df["MONTH"] = df["FL_DATE"].dt.month
df["DAY"] = df["FL_DATE"].dt.day
df["DAY_OF_WEEK"] = df["FL_DATE"].dt.day_name()
df["DAY_OF_WEEK_NUM"] = df["FL_DATE"].dt.dayofweek
df["IS_WEEKEND"] = df["DAY_OF_WEEK_NUM"] >= 5

df[[
    "FL_DATE",
    "YEAR",
    "MONTH",
    "DAY",
    "DAY_OF_WEEK",
    "DAY_OF_WEEK_NUM",
    "IS_WEEKEND"
]].head(10)

     FL_DATE  YEAR  MONTH  DAY DAY_OF_WEEK  DAY_OF_WEEK_NUM  IS_WEEKEND
0 2025-01-01  2025      1    1   Wednesday                2       False
1 2025-01-01  2025      1    1   Wednesday                2       False
2 2025-01-01  2025      1    1   Wednesday                2       False
3 2025-01-01  2025      1    1   Wednesday                2       False
4 2025-01-01  2025      1    1   Wednesday                2       False
5 2025-01-01  2025      1    1   Wednesday                2       False
6 2025-01-01  2025      1    1   Wednesday                2       False
7 2025-01-01  2025      1    1   Wednesday                2       False
8 2025-01-01  2025      1    1   Wednesday                2       False
9 2025-01-01  2025      1    1   Wednesday                2       False

In [ ]:
df[[
    "FL_DATE",
    "CRS_DEP_TIME",
    "DEP_TIME",
    "CRS_ARR_TIME",
    "ARR_TIME"
]].head(20)

df[[
    "CRS_DEP_TIME",
    "DEP_TIME",
    "CRS_ARR_TIME",
    "ARR_TIME"
]].describe()

df[[
    "CRS_DEP_TIME",
    "DEP_TIME",
    "CRS_ARR_TIME",
    "ARR_TIME"
]].isna().sum()

CRS_DEP_TIME        0
DEP_TIME        15886
CRS_ARR_TIME        0
ARR_TIME        16580
dtype: int64

In [ ]:
df[[
    "FL_DATE",
    "CRS_DEP_TIME",
    "DEP_TIME",
    "CRS_ARR_TIME",
    "ARR_TIME"
]].head(20)

      FL_DATE  CRS_DEP_TIME  DEP_TIME  CRS_ARR_TIME  ARR_TIME
0  2025-01-01           659     656.0          1020    1013.0
1  2025-01-01          2200    2153.0           630     543.0
2  2025-01-01           644     720.0          1005    1025.0
3  2025-01-01          1855    1856.0          2134    2127.0
4  2025-01-01           830     829.0          1131    1215.0
5  2025-01-01          1634    1640.0          1927    1922.0
6  2025-01-01          1500    1500.0          1554    1552.0
7  2025-01-01          2042    2036.0          2153    2147.0
8  2025-01-01          1915    1912.0          2125    2117.0
9  2025-01-01          1100    1142.0          1713    1749.0
10 2025-01-01          2040    2249.0          2221      20.0
11 2025-01-01          1227    1241.0          1610    1540.0
12 2025-01-01           700     657.0          1020    1022.0
13 2025-01-01          2140    2137.0          2248    2242.0
14 2025-01-01          1429    1427.0          1609    1555.0
15 2025-01-01          1651    1643.0          1845    1838.0
16 2025-01-01           559     556.0           919     914.0
17 2025-01-01          1846    1841.0           600     555.0
18 2025-01-01           530     521.0           905     925.0
19 2025-01-01          1300    1306.0          1445    1442.0

In [ ]:
# Convert BTS HHMM values into hours and minutes
def time_to_timedelta(series):
    series = series.astype("Int64")
    
    hours = series // 100
    minutes = series % 100
    
    return pd.to_timedelta(hours, unit="h") + pd.to_timedelta(minutes, unit="m")


# Create scheduled timestamps
df["SCHEDULED_DEP_TS"] = (
    df["FL_DATE"] + time_to_timedelta(df["CRS_DEP_TIME"])
)

df["SCHEDULED_ARR_TS"] = (
    df["FL_DATE"] + time_to_timedelta(df["CRS_ARR_TIME"])
)


# Create actual timestamps
df["ACTUAL_DEP_TS"] = (
    df["FL_DATE"] + time_to_timedelta(df["DEP_TIME"])
)

df["ACTUAL_ARR_TS"] = (
    df["FL_DATE"] + time_to_timedelta(df["ARR_TIME"])
)


# Correct overnight scheduled arrivals
overnight_scheduled = (
    df["SCHEDULED_ARR_TS"] < df["SCHEDULED_DEP_TS"]
)

df.loc[overnight_scheduled, "SCHEDULED_ARR_TS"] += pd.Timedelta(days=1)


# Correct overnight actual arrivals
overnight_actual = (
    df["ACTUAL_ARR_TS"] < df["ACTUAL_DEP_TS"]
)

df.loc[overnight_actual, "ACTUAL_ARR_TS"] += pd.Timedelta(days=1)

In [ ]:
df.loc[10, [
    "FL_DATE",
    "CRS_DEP_TIME",
    "DEP_TIME",
    "CRS_ARR_TIME",
    "ARR_TIME",
    "SCHEDULED_DEP_TS",
    "SCHEDULED_ARR_TS",
    "ACTUAL_DEP_TS",
    "ACTUAL_ARR_TS"
]]

FL_DATE             2025-01-01 00:00:00
CRS_DEP_TIME                       2040
DEP_TIME                         2249.0
CRS_ARR_TIME                       2221
ARR_TIME                           20.0
SCHEDULED_DEP_TS    2025-01-01 20:40:00
SCHEDULED_ARR_TS    2025-01-01 22:21:00
ACTUAL_DEP_TS       2025-01-01 22:49:00
ACTUAL_ARR_TS       2025-01-02 00:20:00
Name: 10, dtype: object

In [ ]:
df["CALCULATED_SCHEDULED_DURATION_MIN"] = (
    df["SCHEDULED_ARR_TS"] - df["SCHEDULED_DEP_TS"]
).dt.total_seconds() / 60

df["CALCULATED_ACTUAL_DURATION_MIN"] = (
    df["ACTUAL_ARR_TS"] - df["ACTUAL_DEP_TS"]
).dt.total_seconds() / 60

df[[
    "CRS_ELAPSED_TIME",
    "CALCULATED_SCHEDULED_DURATION_MIN",
    "ACTUAL_ELAPSED_TIME",
    "CALCULATED_ACTUAL_DURATION_MIN"
]].head(20)

,CRS_ELAPSED_TIME,CALCULATED_SCHEDULED_DURATION_MIN,ACTUAL_ELAPSED_TIME,CALCULATED_ACTUAL_DURATION_MIN
0,381.0,201.0,377.0,197.0
1,330.0,510.0,290.0,470.0
2,141.0,201.0,125.0,185.0
3,339.0,159.0,331.0,151.0
4,241.0,181.0,286.0,226.0
5,113.0,173.0,102.0,162.0
6,114.0,54.0,112.0,52.0
7,131.0,71.0,131.0,71.0
8,130.0,130.0,125.0,125.0
9,253.0,373.0,247.0,367.0
10,101.0,101.0,91.0,91.0
11,223.0,223.0,179.0,179.0
12,140.0,200.0,145.0,205.0
13,128.0,68.0,125.0,65.0
14,160.0,100.0,148.0,88.0
15,114.0,114.0,115.0,115.0
16,140.0,200.0,138.0,198.0
17,434.0,674.0,434.0,674.0
18,215.0,215.0,244.0,244.0
19,105.0,105.0,96.0,96.0

In [ ]:
df["SCHEDULED_DURATION_DIFF"] = (
    df["CALCULATED_SCHEDULED_DURATION_MIN"]
    - df["CRS_ELAPSED_TIME"]
)

df["ACTUAL_DURATION_DIFF"] = (
    df["CALCULATED_ACTUAL_DURATION_MIN"]
    - df["ACTUAL_ELAPSED_TIME"]
)

In [ ]:
df[[
    "SCHEDULED_DURATION_DIFF",
    "ACTUAL_DURATION_DIFF"
]].describe()

       SCHEDULED_DURATION_DIFF  ACTUAL_DURATION_DIFF
count            539747.000000         522269.000000
mean                  0.846889              2.562473
std                  75.670336             89.412980
min                -300.000000           -300.000000
25%                 -60.000000            -60.000000
50%                   0.000000              0.000000
75%                  60.000000             60.000000
max                1380.000000           1380.000000

In [11]:
import sys
from pathlib import Path

PROJECT_ROOT = Path.cwd().parent

sys.path.insert(0, str(PROJECT_ROOT))

from src.ingestion import load_bts_flight_data

In [16]:
raw_df = load_bts_flight_data(2025, 1)

Loading: D:\Projects\Flight Logs\data\raw\bts\2025\01\Jan2025.csv
Loaded 539,747 rows and 54 columns.

In [13]:
raw_df.head()
raw_df.shape

(539747, 54)

In [15]:
print(f"Rows: {len(raw_df):,}")
print(f"Columns: {len(raw_df.columns)}")
raw_df.columns.tolist()

Rows: 539,747
Columns: 54

['YEAR',
 'MONTH',
 'FL_DATE',
 'OP_UNIQUE_CARRIER',
 'OP_CARRIER_FL_NUM',
 'ORIGIN_AIRPORT_ID',
 'ORIGIN',
 'ORIGIN_CITY_NAME',
 'ORIGIN_STATE_ABR',
 'ORIGIN_STATE_NM',
 'DEST_AIRPORT_ID',
 'DEST',
 'DEST_CITY_NAME',
 'DEST_STATE_ABR',
 'CRS_DEP_TIME',
 'DEP_TIME',
 'DEP_DELAY',
 'DEP_DELAY_NEW',
 'DEP_DEL15',
 'DEP_DELAY_GROUP',
 'DEP_TIME_BLK',
 'TAXI_OUT',
 'WHEELS_OFF',
 'WHEELS_ON',
 'TAXI_IN',
 'CRS_ARR_TIME',
 'ARR_TIME',
 'ARR_DELAY',
 'ARR_DELAY_NEW',
 'ARR_DEL15',
 'ARR_TIME_BLK',
 'CANCELLED',
 'CANCELLATION_CODE',
 'DIVERTED',
 'CRS_ELAPSED_TIME',
 'ACTUAL_ELAPSED_TIME',
 'AIR_TIME',
 'FLIGHTS',
 'DISTANCE',
 'CARRIER_DELAY',
 'WEATHER_DELAY',
 'NAS_DELAY',
 'SECURITY_DELAY',
 'LATE_AIRCRAFT_DELAY',
 'FIRST_DEP_TIME',
 'TOTAL_ADD_GTIME',
 'LONGEST_ADD_GTIME',
 'DIV_AIRPORT_LANDINGS',
 'DIV_REACHED_DEST',
 'DIV_ACTUAL_ELAPSED_TIME',
 'DIV_ARR_DELAY',
 'DIV_DISTANCE',
 'DIV1_AIRPORT',
 'DIV1_AIRPORT_ID']

In [17]:
from src.ingestion import load_bts_flight_data
from src.cleaning import clean_bts_flight_data

In [18]:
clean_df = clean_bts_flight_data(raw_df)

d:\Projects\Flight Logs\src\cleaning.py:20: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df["FL_DATE"] = pd.to_datetime(

In [19]:
print("Raw shape:   ", raw_df.shape)
print("Clean shape: ", clean_df.shape)

Raw shape:    (539747, 54)
Clean shape:  (539747, 69)

In [20]:
clean_df.columns.tolist()

['YEAR',
 'MONTH',
 'FL_DATE',
 'OP_UNIQUE_CARRIER',
 'OP_CARRIER_FL_NUM',
 'ORIGIN_AIRPORT_ID',
 'ORIGIN',
 'ORIGIN_CITY_NAME',
 'ORIGIN_STATE_ABR',
 'ORIGIN_STATE_NM',
 'DEST_AIRPORT_ID',
 'DEST',
 'DEST_CITY_NAME',
 'DEST_STATE_ABR',
 'CRS_DEP_TIME',
 'DEP_TIME',
 'DEP_DELAY',
 'DEP_DELAY_NEW',
 'DEP_DEL15',
 'DEP_DELAY_GROUP',
 'DEP_TIME_BLK',
 'TAXI_OUT',
 'WHEELS_OFF',
 'WHEELS_ON',
 'TAXI_IN',
 'CRS_ARR_TIME',
 'ARR_TIME',
 'ARR_DELAY',
 'ARR_DELAY_NEW',
 'ARR_DEL15',
 'ARR_TIME_BLK',
 'CANCELLED',
 'CANCELLATION_CODE',
 'DIVERTED',
 'CRS_ELAPSED_TIME',
 'ACTUAL_ELAPSED_TIME',
 'AIR_TIME',
 'FLIGHTS',
 'DISTANCE',
 'CARRIER_DELAY',
 'WEATHER_DELAY',
 'NAS_DELAY',
 'SECURITY_DELAY',
 'LATE_AIRCRAFT_DELAY',
 'FIRST_DEP_TIME',
 'TOTAL_ADD_GTIME',
 'LONGEST_ADD_GTIME',
 'DIV_AIRPORT_LANDINGS',
 'DIV_REACHED_DEST',
 'DIV_ACTUAL_ELAPSED_TIME',
 'DIV_ARR_DELAY',
 'DIV_DISTANCE',
 'DIV1_AIRPORT',
 'DIV1_AIRPORT_ID',
 'DAY',
 'DAY_OF_WEEK',
 'DAY_OF_WEEK_NUM',
 'IS_WEEKEND',
 'FLIGHT_STATUS',
 'IS_COMPLETED',
 'IS_CANCELLED',
 'IS_DIVERTED',
 'DEP_DELAY_ELIGIBLE',
 'ARR_DELAY_ELIGIBLE',
 'DEP_DELAYED_15',
 'ARR_DELAYED_15',
 'DEP_DELAY_CATEGORY',
 'ARR_DELAY_CATEGORY',
 'ROUTE']

In [23]:
clean_df[
    [
        "FL_DATE",
        "OP_UNIQUE_CARRIER",
        "ORIGIN",
        "DEST",
        "ROUTE",
        "FLIGHT_STATUS",
        "DEP_DELAY",
        "ARR_DELAY",
        "DEP_DELAY_CATEGORY",
        "ARR_DELAY_CATEGORY"
    ]
].head(10)

,FL_DATE,OP_UNIQUE_CARRIER,ORIGIN,DEST,ROUTE,FLIGHT_STATUS,DEP_DELAY,ARR_DELAY,DEP_DELAY_CATEGORY,ARR_DELAY_CATEGORY
0,2025-01-01,AA,JFK,LAX,JFK-LAX,COMPLETED,-3.0,-7.0,Early,Early
1,2025-01-01,AA,LAX,JFK,LAX-JFK,COMPLETED,-7.0,-47.0,Early,Early
2,2025-01-01,AA,MSN,CLT,MSN-CLT,COMPLETED,36.0,20.0,30-59 min,15-29 min
3,2025-01-01,AA,PHL,LAS,PHL-LAS,COMPLETED,1.0,-7.0,1-14 min,Early
4,2025-01-01,AA,ORD,PHX,ORD-PHX,COMPLETED,-1.0,44.0,Early,30-59 min
5,2025-01-01,AA,COS,DFW,COS-DFW,COMPLETED,6.0,-5.0,1-14 min,Early
6,2025-01-01,AA,DFW,COS,DFW-COS,COMPLETED,0.0,-2.0,On Time,Early
7,2025-01-01,AA,CLT,STL,CLT-STL,COMPLETED,-6.0,-6.0,Early,Early
8,2025-01-01,AA,LGA,CLT,LGA-CLT,COMPLETED,-3.0,-8.0,Early,Early
9,2025-01-01,AA,EGE,MIA,EGE-MIA,COMPLETED,42.0,36.0,30-59 min,30-59 min

In [31]:
validation_results = validate_flight_data(clean_df)

validation_summary(validation_results)

                         CHECK  VALUE STATUS
0               duplicate_rows      0   PASS
1          missing_flight_date      0   PASS
2               invalid_status      0   PASS
3            negative_distance      0   PASS
4  negative_scheduled_duration      0   PASS
5         cancelled_with_delay      0   PASS
6       cancelled_and_diverted      0   PASS

In [40]:
from src.transformations import create_flight_fact_table

In [52]:
from src.transformations import create_flight_fact_table

import src.transformations
importlib.reload(src.transformations)
flight_fact = create_flight_fact_table(clean_df)
print(flight_fact.shape)
flight_fact.head()
flight_fact.columns.tolist()

(539747, 32)

['flight_date',
 'carrier',
 'flight_number',
 'origin',
 'destination',
 'route',
 'scheduled_departure',
 'actual_departure',
 'scheduled_arrival',
 'actual_arrival',
 'scheduled_duration_min',
 'actual_duration_min',
 'air_time_min',
 'taxi_out_min',
 'taxi_in_min',
 'departure_delay_min',
 'arrival_delay_min',
 'departure_delayed_15',
 'arrival_delayed_15',
 'departure_delay_category',
 'arrival_delay_category',
 'flight_status',
 'is_completed',
 'is_cancelled',
 'is_diverted',
 'distance_miles',
 'year',
 'month',
 'day',
 'day_of_week',
 'day_of_week_num',
 'is_weekend']

In [55]:
import importlib
import src.transformations

importlib.reload(src.transformations)

from src.transformations import create_flight_fact_table

flight_fact = create_flight_fact_table(clean_df)

In [ ]:
flight_fact[
    [
        "flight_id",
        "flight_date",
        "carrier",
        "flight_number",
        "origin",
        "destination"
    ]
].head()
print("Rows:", len(flight_fact))
print("Unique flight IDs:", flight_fact["flight_id"].nunique())

,flight_id,flight_date,carrier,flight_number,origin,destination
0,20250101_AA_1_JFK_LAX,2025-01-01,AA,1,JFK,LAX
1,20250101_AA_10_LAX_JFK,2025-01-01,AA,10,LAX,JFK
2,20250101_AA_1002_MSN_CLT,2025-01-01,AA,1002,MSN,CLT
3,20250101_AA_1004_PHL_LAS,2025-01-01,AA,1004,PHL,LAS
4,20250101_AA_1005_ORD_PHX,2025-01-01,AA,1005,ORD,PHX